const Employes = [
  {
    id: 1,
    first_name: "Grace",
    last_name: "Miller",
    email: "gracemiller12@gmail.com",
    Age: 32,
    phone: "9876543210",
    gender: "female",
    Birthdate: "07-03-1989",
    Country: "USA",
    State: "California",
  },
  {
    id: 2,
    first_name: "John",
    last_name: "Doe",
    email: "johndoe@example.com",
    Age: 45,
    phone: "1234567890",
    gender: "male",
    Birthdate: "11-20-1978",
    Country: "Canada",
    State: "Ontario",
  },
  {
    id: 3,
    first_name: "Alicia",
    last_name: "Smith",
    email: "aliciasmith99@hotmail.com",
    Age: 27,
    phone: "9988776655",
    gender: "female",
    Birthdate: "06-12-1994",
    Country: "Australia",
    State: "Victoria",
  },
  {
    id: 4,
    first_name: "David",
    last_name: "Johnson",
    email: "davidjohnson76@yahoo.com",
    Age: 38,
    phone: "7778889990",
    gender: "male",
    Birthdate: "04-05-1985",
    Country: "UK",
    State: "London",
  },
  {
    id: 5,
    first_name: "Maria",
    last_name: "Garcia",
    email: "mariagarcia@gmail.com",
    Age: 29,
    phone: "5554443330",
    gender: "female",
    Birthdate: "09-22-1992",
    Country: "Mexico",
    State: "Jalisco",
  },
  {
    id: 6,
    first_name: "Juan",
    last_name: "Ramirez",
    email: "juanramirez@gmail.com",
    Age: 41,
    phone: "1122334455",
    gender: "male",
    Birthdate: "01-30-1982",
    Country: "Spain",
    State: "Madrid",
  },
  {
    id: 7,
    first_name: "Emily",
    last_name: "Taylor",
    email: "emilytaylor23@hotmail.com",
    Age: 23,
    phone: "6667778880",
    gender: "female",
    Birthdate: "03-17-2000",
    Country: "USA",
    State: "Florida",
  },
  {
    id: 8,
    first_name: "Michael",
    last_name: "Brown",
    email: "michaelbrown80@yahoo.com",
    Age: 36,
    phone: "4445556660",
    gender: "male",
    Birthdate: "12-10-1987",
    Country: "Canada",
    State: "Quebec",
  },
];
export default Employes;
